routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
    
    Route::group(['prefix' => 'administrator'], function () {


        Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
        Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');
        
        // Password Reset Routes...
        
        Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
        Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
        Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
        Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');
        
    });
    
    Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {
        
        Route::get('/', 'Admin\HomeController@index')->name('home');
        Route::get('/home', 'Admin\HomeController@index')->name('admin.home');
    
    
        // administrators --- Admin Panel users
        // add admin or some one who controll Or help for admin panel
    
        Route::resource('helpAdmin', 'Admin\HelpAdminController');
        Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
        Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
        Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
        Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
        Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
        // Roles routes ..........
        Route::resource('roles', 'Admin\RolesController');
        Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');
    
    
        Route::resource('users', 'Admin\UsersController');
        Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');
    
        Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
                Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
        Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
        Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');

        Route::resource('faqs', 'Admin\FaqsController');

        Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
        Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');


        Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');
    
        Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
        Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
        Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
        Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


        Route::resource('supports', 'Admin\SupportsController');
        Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');

        Route::resource('types', 'Admin\TypesSupportController');

        Route::get('public/notifications', 'Admin\NotificationsController@publicNotifications')->name('public.notifications');
        Route::get('public/notifications/create', 'Admin\NotificationsController@createPublicNotifications')->name('create.public.notifications');
        Route::get('public/notifications/problems', 'Admin\NotificationsController@problems')->name('public.notifications.problems');

        Route::post('send/public/notifications', 'Admin\NotificationsController@sendPublicNotifications')->name('send.public.notifications');
        Route::post('notifications/delete', 'Admin\NotificationsController@delete')->name('notification.delete');


        Route::post('city/delete/group', 'Admin\CitiesController@groupDelete')->name('cities.group.delete');
        Route::post('cities/delete', 'Admin\CitiesController@delete')->name('city.delete');
        Route::resource('cities', 'Admin\CitiesController');
        Route::post('city/suspend', 'Admin\CitiesController@suspend')->name('city.suspend');

        // -------------------------------------- categories .................
        Route::resource('categories', 'Admin\CategoriesController');
        Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
        Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');


        Route::resource('ads', 'Admin\AdsController');
        Route::post('ads/suspend', 'Admin\AdsController@suspend')->name('ads.suspend');


        Route::resource('banks', 'Admin\BanksController');
        Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');


        Route::resource('reports', 'Admin\ReportsController');
        
        Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');
        
    });
    
        Route::get('/landing', 'LandingPageController@index')->name('langPage.index');
        
        Route::get('/share', 'LandingPageController@share')->name('langPage.share');
        
        Route::post('user/update/token', function (Request $request) {

    $user = \App\User::whereId($request->id)->first();


    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }


})->name('user.update.token');
        
         
    

    
    
    
    
    

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
class Faq extends Model
{


    protected $fillable = ['question','answer'];

}

app/Http/Controllers/Admin/FaqsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Faq;
use Validator;
use Illuminate\Support\Facades\Gate;

class FaqsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $faqs = Faq::latest()->get();

        return view('admin.faqs.index',compact('faqs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.faqs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = new Faq;
        $model->question = $request->question;
        $model->answer = $request->answer;

        if ($model->save()) {
            session()->flash('success', 'لقد تم إضافة سؤال بنجاح ' . "($model->question)");
            return redirect(route('faqs.index'));
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faq = Faq::whereId($id)->first();
        if (!$faq) {
            abort(404);
        }

        return view('admin.faqs.edit',compact('faq'));
    }


    public function update(Request $request, $id)
    {
        if (!Gate::allows('users_manage')) {
            return abort(401);
        }

        $model = Faq::findOrFail($id);
        $model->question = $request->question;
        $model->answer = $request->answer;
        $model->save();
        session()->flash('success', 'لقد تم تعديل السؤال بنجاح.');
        return redirect()->route('faqs.index');
    }


    public function destroy($id)
    {
        $model = Faq::findOrFail($id);

        if ($model->delete()) {
            return response()->json([
                'status' => true,
                'data' => $model->id
            ]);
        }
    }
}

resources/views/admin/faqs/create.blade.php
@extends('admin.layouts.master')

@section('title',  __('maincp.common_questions') )



@section('styles')


    <style>
        .dropify-wrapper {
            height: 180px !important;
        }
    </style>
@endsection
@section('content')

    <div id="messageError"></div>
    <form data-parsley-validate novalidate method="POST" action="{{ route('faqs.store') }}"
          enctype="multipart/form-data">
    {{ csrf_field() }}
    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12 ">
                <div class="btn-group pull-right m-t-15">


                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> @lang('maincp.back') <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>


                </div>
                <h4 class="page-title">@lang('maincp.common_questions')</h4>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12 ">
                <div class="card-box">
                    <h4 class="header-title m-t-0 m-b-30">@lang('maincp.add_new_item')</h4>

                    <div class="form-group">
                        <label for="userName">@lang('maincp.question') *</label>
                        <input type="text" name="question" data-parsley-trigger="keyup" required
                               placeholder="@lang('maincp.question')..." class="form-control description"
                               id="userName" 
                               data-parsley-required-message="هذا الحقل إلزامي">
                    </div>


                    <div class="form-group">
                        <label for="userName">@lang('maincp.answer')*</label>


                        <textarea class="form-control msg_body" name="answer" required  data-parsley-required-message="هذا الحقل إلزامي" 
                        	data-parsley-trigger="keyup" placeholder="@lang('maincp.answer')..."></textarea>
                    </div>



                    <div class="form-group text-right m-b-0 ">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">@lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">@lang('maincp.disable')  
                        </button>
                    </div>


                </div>
            </div><!-- end col -->

            {{--<div class="col-lg-4">
                <div class="card-box" style="overflow: hidden;">

                    <h4 class="header-title m-t-0 m-b-30">شعار العلامة التجارية</h4>

                    <div class="form-group">
                        <input type="file" name="image" class="dropify" data-max-file-size="6M"/>
                    </div>

                </div>
            </div>--}}


        </div>
        <!-- end row -->
    </form>


@endsection


@section('scripts')

    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>



    {{--<script type="text/javascript">--}}

    {{--$('form').on('submit', function (e) {--}}
    {{--e.preventDefault();--}}
    {{--var formData = new FormData(this);--}}
    {{--$.ajax({--}}
    {{--type: 'POST',--}}
    {{--url: $(this).attr('action'),--}}
    {{--data: formData,--}}
    {{--cache: false,--}}
    {{--contentType: false,--}}
    {{--processData: false,--}}
    {{--success: function (data) {--}}

    {{--//  $('#messageError').html(data.message);--}}

    {{--var shortCutFunction = 'success';--}}
    {{--var msg = data.message;--}}
    {{--var title = 'نجاح';--}}
    {{--toastr.options = {--}}
    {{--positionClass: 'toast-top-left',--}}
    {{--onclick: null--}}
    {{--};--}}
    {{--var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists--}}
    {{--$toastlast = $toast;--}}
    {{--setTimeout(function () {--}}
    {{--window.location.href = '{{ route('categories.index') }}';--}}
    {{--}, 3000);--}}
    {{--},--}}
    {{--error: function (data) {--}}

    {{--}--}}
    {{--});--}}
    {{--});--}}

    {{--</script>--}}
@endsection

resources/views/admin/faqs/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.common_questions'))
@section('content')

    <div id="messageError"></div>
    <form data-parsley-validate novalidate method="POST" action="{{ route('faqs.update', $faq->id) }}"
          enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('PUT') }}
        
    <!-- Page-Title -->
        <div class="row">
              <div class="col-lg-12 ">
                <div class="btn-group pull-right m-t-15">
                    <a href="{{ route('faqs.index') }}" class="btn btn-custom waves-effect waves-light"> رجوع <span
                                class="m-l-5">
                            <i class="fa fa-reply"></i></span>
                    </a>
                </div>
                <h4 class="page-title">  @lang('maincp.common_questions')</h4>
            </div>
        </div>

        <div class="row">
               <div class="col-lg-12 ">
                <div class="card-box">
                    <h4 class="header-title m-t-0 m-b-30"> @lang('maincp.edit_question')( {{ $faq->question }} )</h4>

                    <div class="form-group">
                        <label for="userName">@lang('maincp.name')*</label>
                        <input type="text" name="question" data-parsley-trigger="keyup" required
                               placeholder="نوع البطارية..." class="form-control description"
                               id="userName" value="{{ $faq->question  }}"

                               data-parsley-required-message="هذا الحقل إلزامي">
                    </div>


                    <div class="form-group">
                        <label for="userName">@lang('maincp.answer')*</label>


                        <textarea class="form-control msg_body" name="answer" required  data-parsley-required-message="هذا الحقل إلزامي" data-parsley-trigger="keyup" placeholder="الإجابة...">{{ $faq->answer }}</textarea>
                    </div>




                    <div class="form-group text-right m-b-0 ">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit"> @lang('maincp.save_data')  
                        </button>
                        <button onclick="window.history.back();return false;"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20"> @lang('maincp.disable') 
                        </button>
                    </div>


                </div>
            </div><!-- end col -->




        </div>


        <!-- end row -->
    </form>


@endsection

@section('scripts')
    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>

@endsection


{{--<script type="text/javascript">--}}

{{--$('form').on('submit', function (e) {--}}
{{--e.preventDefault();--}}
{{--var formData = new FormData(this);--}}
{{--$.ajax({--}}
{{--type: 'POST',--}}
{{--url: $(this).attr('action'),--}}
{{--data: formData,--}}
{{--cache: false,--}}
{{--contentType: false,--}}
{{--processData: false,--}}
{{--success: function (data) {--}}

{{--//  $('#messageError').html(data.message);--}}

{{--var shortCutFunction = 'success';--}}
{{--var msg = data.message;--}}
{{--var title = 'نجاح';--}}
{{--toastr.options = {--}}
{{--positionClass: 'toast-top-left',--}}
{{--onclick: null--}}
{{--};--}}
{{--var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists--}}
{{--$toastlast = $toast;--}}
{{--setTimeout(function () {--}}
{{--window.location.href = '{{ route('categories.index') }}';--}}
{{--}, 3000);--}}
{{--},--}}
{{--error: function (data) {--}}

{{--}--}}
{{--});--}}
{{--});--}}

{{--</script>--}}
{{--@endsection--}}

resources/views/admin/faqs/index.blade.php
@extends('admin.layouts.master')
@php


    $title =  __('maincp.common_questions');

@endphp

@section('title' , $title)
@section('content')

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">

                <a href="{{ route('faqs.create') }}" class="btn btn-custom waves-effect waves-light">@lang('maincp.add') <span
                            class="m-l-5">
                            <i class="fa fa-plus"></i></span>
                </a>

            </div>
            <h4 class="page-title">{{ $title }}</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">

                <h4 class="header-title m-t-0 m-b-30">@lang('maincp.view_common_questions')</h4>

                <table id="datatable-fixed-header" class="table table-bordered table-hover">
                    <thead>
                    <tr>

                        <th>@lang('maincp.question')</th>
                        <th> @lang('maincp.answer')</th>
                        <th>@lang('maincp.choose')</th>

                    </tr>
                    </thead>
                    <tbody>


                    @foreach($faqs as $row)
                        <tr>
                            <td>{{ $row->question }}</td>
                            <td>{{ $row->answer }}</td>

                            {{--<td>{{ $row->created_at }}</td>--}}
                            <td>
                                <a href="{{ route('faqs.edit', $row->id) }}"
                                   class="btn btn-icon btn-xs waves-effect btn-default m-b-5">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="javascript:;" id="elementRow{{ $row->id }}" data-id="{{ $row->id }}"
                                   data-url="{{ route('faqs.destroy', $row) }}"
                                   class="removeElement btn btn-icon btn-trans btn-xs waves-effect waves-light btn-danger m-b-5">
                                    <i class="fa fa-remove"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>



            </div>
        </div><!-- end col -->

    </div>
    <!-- end row -->
@endsection


@section('scripts')



    <script>

        $('body').on('click', '.removeElement', function () {
            var id = $(this).attr('data-id');
            var $tr = $(this).closest($('#elementRow' + id).parent().parent());
            var url = $(this).attr('data-url');
            swal({
                title: "هل انت متأكد؟",
                text: "يمكنك استرجاع المحذوفات مرة اخرى لا تقلق.",
                type: "error",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "موافق",
                cancelButtonText: "إلغاء",
                confirmButtonClass: 'btn-danger waves-effect waves-light',
                closeOnConfirm: true,
                closeOnCancel: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: 'DELETE',
                        url: url,
                        data: {id: id},
                        dataType: 'json',
                        success: function (data) {
                            if (data.status == true) {
                                var shortCutFunction = 'success';
                                var msg = 'لقد تمت عملية الحذف بنجاح.';
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;

                                $tr.find('td').fadeOut(1000, function () {
                                    $tr.remove();
                                });
                            }
                            if (data.status == false) {
                                var shortCutFunction = 'error';
                                var msg = data.message;
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;
                            }
                        }
                    });
                } else {

                    swal({
                        title: "تم الالغاء",
                        text: "انت لغيت عملية الحذف تقدر تحاول فى اى وقت :)",
                        type: "error",
                        showCancelButton: false,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "موافق",
                        confirmButtonClass: 'btn-info waves-effect waves-light',
                        closeOnConfirm: false,
                        closeOnCancel: false

                    });

                }
            });
        });


    </script>


@endsection